### ISSUE TITLE
V2 Plugin: asciiator

### ISSUE THREAD

**Issue by manparvesh** [manparvesh/yoda#305]
https://github.com/yoda-pa/yoda/blob/master/modules/asciiator.py

**Comment by vatsal-afk** [comment]
hey @manparvesh I have written a function for the same, how would you like the output to be displayed in the terminal or saved as a separate new file?

**Comment by manparvesh** [comment]
@vatsal-afk the PR you have for this is a good one, please see my comments on it and make the required changes and we should be good to merge it
