### ISSUE TITLE
V2 Plugin: Weather

### ISSUE THREAD

**Issue by manparvesh** [manparvesh/yoda#314]
**What would you like to be added**:  A Plugin for yoda that allows you to get weather details for a location

**Any ideas you might have for implementation**: The v1 version of yoda implemented it like this, you can get ideas on implementation from there: https://github.com/yoda-pa/yoda/blob/v1/modules/weather.py

**Comment by vatsal-afk** [comment]
Hi! It would be very helpful if you could be more specific with the issue or the feature you want to add. Thanks!

**Comment by manparvesh** [comment]
@vatsal-afk I updated the description

**Comment by vatsal-afk** [comment]
please, can you assign the issue

**Comment by vatsal-afk** [comment]
![image](https://github.com/user-attachments/assets/818fdb03-f933-4615-899b-e8baa5bf6387)


is this output for the user fine? @manparvesh pls review this to avoid premature PRs
