### ISSUE TITLE
An error occurred: unable to open database file

### ISSUE THREAD

**Issue by vatsal-afk** [manparvesh/yoda#317]
![Screenshot from 2024-10-14 17-28-51](https://github.com/user-attachments/assets/59d18163-fc4a-4c6d-bc31-2a2312ce5679)

 @manparvesh 
How to fix this?

**Comment by manparvesh** [comment]
did you run `yoda init`?

**Comment by vatsal-afk** [comment]
yes, similar error persists: poetry run yoda init
Yoda config not initialized. Use `yoda init` to initialize
Usage: yoda [OPTIONS]
Try 'yoda --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Got unexpected extra argument (init)

**Comment by vatsal-afk** [comment]
it works now :)

**Comment by manparvesh** [comment]
how did you fix it?
